//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://schemas.microsoft.com/sharepoint/taxonomy/soap/", ClrNamespace="schemas.microsoft.com.sharepoint.taxonomy.soap")]

namespace schemas.microsoft.com.sharepoint.taxonomy.soap
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StringMatchOption", Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/")]
    public enum StringMatchOption : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StartsWith = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExactMatch = 1,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Name="Taxonomy web serviceSoap", Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/", ConfigurationName="TaxonomywebserviceSoap")]
public interface TaxonomywebserviceSoap
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/taxonomy/soap/GetTermSets", ReplyAction="*")]
    GetTermSetsResponse GetTermSets(GetTermSetsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/taxonomy/soap/GetTermSets", ReplyAction="*")]
    System.Threading.Tasks.Task<GetTermSetsResponse> GetTermSetsAsync(GetTermSetsRequest request);
    
    // CODEGEN: Generating message contract since element name label from namespace http://schemas.microsoft.com/sharepoint/taxonomy/soap/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/taxonomy/soap/GetTermsByLabel", ReplyAction="*")]
    GetTermsByLabelResponse GetTermsByLabel(GetTermsByLabelRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/taxonomy/soap/GetTermsByLabel", ReplyAction="*")]
    System.Threading.Tasks.Task<GetTermsByLabelResponse> GetTermsByLabelAsync(GetTermsByLabelRequest request);
    
    // CODEGEN: Generating message contract since element name newTerms from namespace http://schemas.microsoft.com/sharepoint/taxonomy/soap/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/taxonomy/soap/AddTerms", ReplyAction="*")]
    AddTermsResponse AddTerms(AddTermsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/taxonomy/soap/AddTerms", ReplyAction="*")]
    System.Threading.Tasks.Task<AddTermsResponse> AddTermsAsync(AddTermsRequest request);
    
    // CODEGEN: Generating message contract since element name termIds from namespace http://schemas.microsoft.com/sharepoint/taxonomy/soap/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/taxonomy/soap/GetKeywordTermsByGuids", ReplyAction="*")]
    GetKeywordTermsByGuidsResponse GetKeywordTermsByGuids(GetKeywordTermsByGuidsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/taxonomy/soap/GetKeywordTermsByGuids", ReplyAction="*")]
    System.Threading.Tasks.Task<GetKeywordTermsByGuidsResponse> GetKeywordTermsByGuidsAsync(GetKeywordTermsByGuidsRequest request);
    
    // CODEGEN: Generating message contract since element name GetChildTermsInTermSetResult from namespace http://schemas.microsoft.com/sharepoint/taxonomy/soap/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/taxonomy/soap/GetChildTermsInTermSet", ReplyAction="*")]
    GetChildTermsInTermSetResponse GetChildTermsInTermSet(GetChildTermsInTermSetRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/taxonomy/soap/GetChildTermsInTermSet", ReplyAction="*")]
    System.Threading.Tasks.Task<GetChildTermsInTermSetResponse> GetChildTermsInTermSetAsync(GetChildTermsInTermSetRequest request);
    
    // CODEGEN: Generating message contract since element name GetChildTermsInTermResult from namespace http://schemas.microsoft.com/sharepoint/taxonomy/soap/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/taxonomy/soap/GetChildTermsInTerm", ReplyAction="*")]
    GetChildTermsInTermResponse GetChildTermsInTerm(GetChildTermsInTermRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/taxonomy/soap/GetChildTermsInTerm", ReplyAction="*")]
    System.Threading.Tasks.Task<GetChildTermsInTermResponse> GetChildTermsInTermAsync(GetChildTermsInTermRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetTermSetsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTermSets", Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/", Order=0)]
    public GetTermSetsRequestBody Body;
    
    public GetTermSetsRequest()
    {
    }
    
    public GetTermSetsRequest(GetTermSetsRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/")]
public partial class GetTermSetsRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sharedServiceIds;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string termSetIds;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    public int lcid;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string clientTimeStamps;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
    public string clientVersions;
    
    public GetTermSetsRequestBody()
    {
    }
    
    public GetTermSetsRequestBody(string sharedServiceIds, string termSetIds, int lcid, string clientTimeStamps, string clientVersions)
    {
        this.sharedServiceIds = sharedServiceIds;
        this.termSetIds = termSetIds;
        this.lcid = lcid;
        this.clientTimeStamps = clientTimeStamps;
        this.clientVersions = clientVersions;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetTermSetsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTermSetsResponse", Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/", Order=0)]
    public GetTermSetsResponseBody Body;
    
    public GetTermSetsResponse()
    {
    }
    
    public GetTermSetsResponse(GetTermSetsResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/")]
public partial class GetTermSetsResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetTermSetsResult;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string serverTermSetTimeStampXml;
    
    public GetTermSetsResponseBody()
    {
    }
    
    public GetTermSetsResponseBody(string GetTermSetsResult, string serverTermSetTimeStampXml)
    {
        this.GetTermSetsResult = GetTermSetsResult;
        this.serverTermSetTimeStampXml = serverTermSetTimeStampXml;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetTermsByLabelRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTermsByLabel", Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/", Order=0)]
    public GetTermsByLabelRequestBody Body;
    
    public GetTermsByLabelRequest()
    {
    }
    
    public GetTermsByLabelRequest(GetTermsByLabelRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/")]
public partial class GetTermsByLabelRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string label;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
    public int lcid;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    public schemas.microsoft.com.sharepoint.taxonomy.soap.StringMatchOption matchOption;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
    public int resultCollectionSize;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
    public string termIds;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
    public bool addIfNotFound;
    
    public GetTermsByLabelRequestBody()
    {
    }
    
    public GetTermsByLabelRequestBody(string label, int lcid, schemas.microsoft.com.sharepoint.taxonomy.soap.StringMatchOption matchOption, int resultCollectionSize, string termIds, bool addIfNotFound)
    {
        this.label = label;
        this.lcid = lcid;
        this.matchOption = matchOption;
        this.resultCollectionSize = resultCollectionSize;
        this.termIds = termIds;
        this.addIfNotFound = addIfNotFound;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetTermsByLabelResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTermsByLabelResponse", Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/", Order=0)]
    public GetTermsByLabelResponseBody Body;
    
    public GetTermsByLabelResponse()
    {
    }
    
    public GetTermsByLabelResponse(GetTermsByLabelResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/")]
public partial class GetTermsByLabelResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetTermsByLabelResult;
    
    public GetTermsByLabelResponseBody()
    {
    }
    
    public GetTermsByLabelResponseBody(string GetTermsByLabelResult)
    {
        this.GetTermsByLabelResult = GetTermsByLabelResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class AddTermsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTerms", Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/", Order=0)]
    public AddTermsRequestBody Body;
    
    public AddTermsRequest()
    {
    }
    
    public AddTermsRequest(AddTermsRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/")]
public partial class AddTermsRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public System.Guid sharedServiceId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
    public System.Guid termSetId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    public int lcid;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string newTerms;
    
    public AddTermsRequestBody()
    {
    }
    
    public AddTermsRequestBody(System.Guid sharedServiceId, System.Guid termSetId, int lcid, string newTerms)
    {
        this.sharedServiceId = sharedServiceId;
        this.termSetId = termSetId;
        this.lcid = lcid;
        this.newTerms = newTerms;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class AddTermsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTermsResponse", Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/", Order=0)]
    public AddTermsResponseBody Body;
    
    public AddTermsResponse()
    {
    }
    
    public AddTermsResponse(AddTermsResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/")]
public partial class AddTermsResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string AddTermsResult;
    
    public AddTermsResponseBody()
    {
    }
    
    public AddTermsResponseBody(string AddTermsResult)
    {
        this.AddTermsResult = AddTermsResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetKeywordTermsByGuidsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKeywordTermsByGuids", Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/", Order=0)]
    public GetKeywordTermsByGuidsRequestBody Body;
    
    public GetKeywordTermsByGuidsRequest()
    {
    }
    
    public GetKeywordTermsByGuidsRequest(GetKeywordTermsByGuidsRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/")]
public partial class GetKeywordTermsByGuidsRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string termIds;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
    public int lcid;
    
    public GetKeywordTermsByGuidsRequestBody()
    {
    }
    
    public GetKeywordTermsByGuidsRequestBody(string termIds, int lcid)
    {
        this.termIds = termIds;
        this.lcid = lcid;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetKeywordTermsByGuidsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKeywordTermsByGuidsResponse", Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/", Order=0)]
    public GetKeywordTermsByGuidsResponseBody Body;
    
    public GetKeywordTermsByGuidsResponse()
    {
    }
    
    public GetKeywordTermsByGuidsResponse(GetKeywordTermsByGuidsResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/")]
public partial class GetKeywordTermsByGuidsResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetKeywordTermsByGuidsResult;
    
    public GetKeywordTermsByGuidsResponseBody()
    {
    }
    
    public GetKeywordTermsByGuidsResponseBody(string GetKeywordTermsByGuidsResult)
    {
        this.GetKeywordTermsByGuidsResult = GetKeywordTermsByGuidsResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetChildTermsInTermSetRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetChildTermsInTermSet", Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/", Order=0)]
    public GetChildTermsInTermSetRequestBody Body;
    
    public GetChildTermsInTermSetRequest()
    {
    }
    
    public GetChildTermsInTermSetRequest(GetChildTermsInTermSetRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/")]
public partial class GetChildTermsInTermSetRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public System.Guid sspId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
    public int lcid;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    public System.Guid termSetId;
    
    public GetChildTermsInTermSetRequestBody()
    {
    }
    
    public GetChildTermsInTermSetRequestBody(System.Guid sspId, int lcid, System.Guid termSetId)
    {
        this.sspId = sspId;
        this.lcid = lcid;
        this.termSetId = termSetId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetChildTermsInTermSetResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetChildTermsInTermSetResponse", Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/", Order=0)]
    public GetChildTermsInTermSetResponseBody Body;
    
    public GetChildTermsInTermSetResponse()
    {
    }
    
    public GetChildTermsInTermSetResponse(GetChildTermsInTermSetResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/")]
public partial class GetChildTermsInTermSetResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetChildTermsInTermSetResult;
    
    public GetChildTermsInTermSetResponseBody()
    {
    }
    
    public GetChildTermsInTermSetResponseBody(string GetChildTermsInTermSetResult)
    {
        this.GetChildTermsInTermSetResult = GetChildTermsInTermSetResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetChildTermsInTermRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetChildTermsInTerm", Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/", Order=0)]
    public GetChildTermsInTermRequestBody Body;
    
    public GetChildTermsInTermRequest()
    {
    }
    
    public GetChildTermsInTermRequest(GetChildTermsInTermRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/")]
public partial class GetChildTermsInTermRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public System.Guid sspId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
    public int lcid;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    public System.Guid termId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
    public System.Guid termSetId;
    
    public GetChildTermsInTermRequestBody()
    {
    }
    
    public GetChildTermsInTermRequestBody(System.Guid sspId, int lcid, System.Guid termId, System.Guid termSetId)
    {
        this.sspId = sspId;
        this.lcid = lcid;
        this.termId = termId;
        this.termSetId = termSetId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetChildTermsInTermResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetChildTermsInTermResponse", Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/", Order=0)]
    public GetChildTermsInTermResponseBody Body;
    
    public GetChildTermsInTermResponse()
    {
    }
    
    public GetChildTermsInTermResponse(GetChildTermsInTermResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/taxonomy/soap/")]
public partial class GetChildTermsInTermResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetChildTermsInTermResult;
    
    public GetChildTermsInTermResponseBody()
    {
    }
    
    public GetChildTermsInTermResponseBody(string GetChildTermsInTermResult)
    {
        this.GetChildTermsInTermResult = GetChildTermsInTermResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface TaxonomywebserviceSoapChannel : TaxonomywebserviceSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TaxonomywebserviceSoapClient : System.ServiceModel.ClientBase<TaxonomywebserviceSoap>, TaxonomywebserviceSoap
{
    
    public TaxonomywebserviceSoapClient()
    {
    }
    
    public TaxonomywebserviceSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TaxonomywebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TaxonomywebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TaxonomywebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetTermSetsResponse TaxonomywebserviceSoap.GetTermSets(GetTermSetsRequest request)
    {
        return base.Channel.GetTermSets(request);
    }
    
    public string GetTermSets(string sharedServiceIds, string termSetIds, int lcid, string clientTimeStamps, string clientVersions, out string serverTermSetTimeStampXml)
    {
        GetTermSetsRequest inValue = new GetTermSetsRequest();
        inValue.Body = new GetTermSetsRequestBody();
        inValue.Body.sharedServiceIds = sharedServiceIds;
        inValue.Body.termSetIds = termSetIds;
        inValue.Body.lcid = lcid;
        inValue.Body.clientTimeStamps = clientTimeStamps;
        inValue.Body.clientVersions = clientVersions;
        GetTermSetsResponse retVal = ((TaxonomywebserviceSoap)(this)).GetTermSets(inValue);
        serverTermSetTimeStampXml = retVal.Body.serverTermSetTimeStampXml;
        return retVal.Body.GetTermSetsResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetTermSetsResponse> TaxonomywebserviceSoap.GetTermSetsAsync(GetTermSetsRequest request)
    {
        return base.Channel.GetTermSetsAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetTermSetsResponse> GetTermSetsAsync(string sharedServiceIds, string termSetIds, int lcid, string clientTimeStamps, string clientVersions)
    {
        GetTermSetsRequest inValue = new GetTermSetsRequest();
        inValue.Body = new GetTermSetsRequestBody();
        inValue.Body.sharedServiceIds = sharedServiceIds;
        inValue.Body.termSetIds = termSetIds;
        inValue.Body.lcid = lcid;
        inValue.Body.clientTimeStamps = clientTimeStamps;
        inValue.Body.clientVersions = clientVersions;
        return ((TaxonomywebserviceSoap)(this)).GetTermSetsAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetTermsByLabelResponse TaxonomywebserviceSoap.GetTermsByLabel(GetTermsByLabelRequest request)
    {
        return base.Channel.GetTermsByLabel(request);
    }
    
    public string GetTermsByLabel(string label, int lcid, schemas.microsoft.com.sharepoint.taxonomy.soap.StringMatchOption matchOption, int resultCollectionSize, string termIds, bool addIfNotFound)
    {
        GetTermsByLabelRequest inValue = new GetTermsByLabelRequest();
        inValue.Body = new GetTermsByLabelRequestBody();
        inValue.Body.label = label;
        inValue.Body.lcid = lcid;
        inValue.Body.matchOption = matchOption;
        inValue.Body.resultCollectionSize = resultCollectionSize;
        inValue.Body.termIds = termIds;
        inValue.Body.addIfNotFound = addIfNotFound;
        GetTermsByLabelResponse retVal = ((TaxonomywebserviceSoap)(this)).GetTermsByLabel(inValue);
        return retVal.Body.GetTermsByLabelResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetTermsByLabelResponse> TaxonomywebserviceSoap.GetTermsByLabelAsync(GetTermsByLabelRequest request)
    {
        return base.Channel.GetTermsByLabelAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetTermsByLabelResponse> GetTermsByLabelAsync(string label, int lcid, schemas.microsoft.com.sharepoint.taxonomy.soap.StringMatchOption matchOption, int resultCollectionSize, string termIds, bool addIfNotFound)
    {
        GetTermsByLabelRequest inValue = new GetTermsByLabelRequest();
        inValue.Body = new GetTermsByLabelRequestBody();
        inValue.Body.label = label;
        inValue.Body.lcid = lcid;
        inValue.Body.matchOption = matchOption;
        inValue.Body.resultCollectionSize = resultCollectionSize;
        inValue.Body.termIds = termIds;
        inValue.Body.addIfNotFound = addIfNotFound;
        return ((TaxonomywebserviceSoap)(this)).GetTermsByLabelAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    AddTermsResponse TaxonomywebserviceSoap.AddTerms(AddTermsRequest request)
    {
        return base.Channel.AddTerms(request);
    }
    
    public string AddTerms(System.Guid sharedServiceId, System.Guid termSetId, int lcid, string newTerms)
    {
        AddTermsRequest inValue = new AddTermsRequest();
        inValue.Body = new AddTermsRequestBody();
        inValue.Body.sharedServiceId = sharedServiceId;
        inValue.Body.termSetId = termSetId;
        inValue.Body.lcid = lcid;
        inValue.Body.newTerms = newTerms;
        AddTermsResponse retVal = ((TaxonomywebserviceSoap)(this)).AddTerms(inValue);
        return retVal.Body.AddTermsResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<AddTermsResponse> TaxonomywebserviceSoap.AddTermsAsync(AddTermsRequest request)
    {
        return base.Channel.AddTermsAsync(request);
    }
    
    public System.Threading.Tasks.Task<AddTermsResponse> AddTermsAsync(System.Guid sharedServiceId, System.Guid termSetId, int lcid, string newTerms)
    {
        AddTermsRequest inValue = new AddTermsRequest();
        inValue.Body = new AddTermsRequestBody();
        inValue.Body.sharedServiceId = sharedServiceId;
        inValue.Body.termSetId = termSetId;
        inValue.Body.lcid = lcid;
        inValue.Body.newTerms = newTerms;
        return ((TaxonomywebserviceSoap)(this)).AddTermsAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetKeywordTermsByGuidsResponse TaxonomywebserviceSoap.GetKeywordTermsByGuids(GetKeywordTermsByGuidsRequest request)
    {
        return base.Channel.GetKeywordTermsByGuids(request);
    }
    
    public string GetKeywordTermsByGuids(string termIds, int lcid)
    {
        GetKeywordTermsByGuidsRequest inValue = new GetKeywordTermsByGuidsRequest();
        inValue.Body = new GetKeywordTermsByGuidsRequestBody();
        inValue.Body.termIds = termIds;
        inValue.Body.lcid = lcid;
        GetKeywordTermsByGuidsResponse retVal = ((TaxonomywebserviceSoap)(this)).GetKeywordTermsByGuids(inValue);
        return retVal.Body.GetKeywordTermsByGuidsResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetKeywordTermsByGuidsResponse> TaxonomywebserviceSoap.GetKeywordTermsByGuidsAsync(GetKeywordTermsByGuidsRequest request)
    {
        return base.Channel.GetKeywordTermsByGuidsAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetKeywordTermsByGuidsResponse> GetKeywordTermsByGuidsAsync(string termIds, int lcid)
    {
        GetKeywordTermsByGuidsRequest inValue = new GetKeywordTermsByGuidsRequest();
        inValue.Body = new GetKeywordTermsByGuidsRequestBody();
        inValue.Body.termIds = termIds;
        inValue.Body.lcid = lcid;
        return ((TaxonomywebserviceSoap)(this)).GetKeywordTermsByGuidsAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetChildTermsInTermSetResponse TaxonomywebserviceSoap.GetChildTermsInTermSet(GetChildTermsInTermSetRequest request)
    {
        return base.Channel.GetChildTermsInTermSet(request);
    }
    
    public string GetChildTermsInTermSet(System.Guid sspId, int lcid, System.Guid termSetId)
    {
        GetChildTermsInTermSetRequest inValue = new GetChildTermsInTermSetRequest();
        inValue.Body = new GetChildTermsInTermSetRequestBody();
        inValue.Body.sspId = sspId;
        inValue.Body.lcid = lcid;
        inValue.Body.termSetId = termSetId;
        GetChildTermsInTermSetResponse retVal = ((TaxonomywebserviceSoap)(this)).GetChildTermsInTermSet(inValue);
        return retVal.Body.GetChildTermsInTermSetResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetChildTermsInTermSetResponse> TaxonomywebserviceSoap.GetChildTermsInTermSetAsync(GetChildTermsInTermSetRequest request)
    {
        return base.Channel.GetChildTermsInTermSetAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetChildTermsInTermSetResponse> GetChildTermsInTermSetAsync(System.Guid sspId, int lcid, System.Guid termSetId)
    {
        GetChildTermsInTermSetRequest inValue = new GetChildTermsInTermSetRequest();
        inValue.Body = new GetChildTermsInTermSetRequestBody();
        inValue.Body.sspId = sspId;
        inValue.Body.lcid = lcid;
        inValue.Body.termSetId = termSetId;
        return ((TaxonomywebserviceSoap)(this)).GetChildTermsInTermSetAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetChildTermsInTermResponse TaxonomywebserviceSoap.GetChildTermsInTerm(GetChildTermsInTermRequest request)
    {
        return base.Channel.GetChildTermsInTerm(request);
    }
    
    public string GetChildTermsInTerm(System.Guid sspId, int lcid, System.Guid termId, System.Guid termSetId)
    {
        GetChildTermsInTermRequest inValue = new GetChildTermsInTermRequest();
        inValue.Body = new GetChildTermsInTermRequestBody();
        inValue.Body.sspId = sspId;
        inValue.Body.lcid = lcid;
        inValue.Body.termId = termId;
        inValue.Body.termSetId = termSetId;
        GetChildTermsInTermResponse retVal = ((TaxonomywebserviceSoap)(this)).GetChildTermsInTerm(inValue);
        return retVal.Body.GetChildTermsInTermResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetChildTermsInTermResponse> TaxonomywebserviceSoap.GetChildTermsInTermAsync(GetChildTermsInTermRequest request)
    {
        return base.Channel.GetChildTermsInTermAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetChildTermsInTermResponse> GetChildTermsInTermAsync(System.Guid sspId, int lcid, System.Guid termId, System.Guid termSetId)
    {
        GetChildTermsInTermRequest inValue = new GetChildTermsInTermRequest();
        inValue.Body = new GetChildTermsInTermRequestBody();
        inValue.Body.sspId = sspId;
        inValue.Body.lcid = lcid;
        inValue.Body.termId = termId;
        inValue.Body.termSetId = termSetId;
        return ((TaxonomywebserviceSoap)(this)).GetChildTermsInTermAsync(inValue);
    }
}
